### ISSUE TITLE
Limits in user/userid/stats and user/userid/scores are wrong

### ISSUE THREAD

**Issue by CrisF-98** [ldeluigi/higher-lower-pwned#88]
Currently working on an app using this API.
Turns out that the "limit" parameter in user/userid/stats and user/userid/scores specified in the wiki are wrong.

For the first url, it works with a max limit of 30.
For the latter, a working max limit is 500.

**Comment by ldeluigi** [comment]
The first one has been fixed.
I can't confirm the second one: from the code perspective it should be 1000. Can you check again?

**Comment by CrisF-98** [comment]
I was wrong on the second one, my bad.
